### ISSUE TITLE
[RFC] Rethink view

### ISSUE THREAD

**Issue by ywzbhpa00** [GreenMashimaro/egg-test#1]
https://github.com/GreenMashimaro/egg-test/blob/57ff6a5030e3b95fbc9f22b80b21bdfbc6a42db1/test/unit/specs/HelloWorld.spec.js#L5

hello, this line!

**Comment by GreenMashimaro** [comment]
@ywzbhpa00 this is right, not error

**Comment by GreenMashimaro** [comment]
#2 link2
